[2025-07-28T12:38:35.364+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_deps scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T12:38:35.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_deps scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T12:38:35.367+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-28T12:38:35.371+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-07-27 00:00:00+00:00
[2025-07-28T12:38:35.373+0000] {standard_task_runner.py:60} INFO - Started process 114 to run task
[2025-07-28T12:38:35.375+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_pipeline', 'dbt_deps', 'scheduled__2025-07-27T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dbt_pipeline.py', '--cfg-path', '/tmp/tmp3aakszmr']
[2025-07-28T12:38:35.377+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask dbt_deps
[2025-07-28T12:38:35.383+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-07-28T12:38:35.402+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_pipeline.dbt_deps scheduled__2025-07-27T00:00:00+00:00 [running]> on host 26b399183f28
[2025-07-28T12:38:35.428+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gotphoto' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-27T00:00:00+00:00'
[2025-07-28T12:38:35.429+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-28T12:38:35.430+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt deps --project-dir . --profiles-dir profiles']
[2025-07-28T12:38:35.434+0000] {subprocess.py:86} INFO - Output:
[2025-07-28T12:38:36.092+0000] {subprocess.py:93} INFO - [0m12:38:36  Running with dbt=1.8.7
[2025-07-28T12:38:36.562+0000] {subprocess.py:93} INFO - [0m12:38:36  Updating lock file in file path: /opt/***/dbt_project/package-lock.yml
[2025-07-28T12:38:36.950+0000] {subprocess.py:93} INFO - [0m12:38:36  Installing dbt-labs/dbt_utils
[2025-07-28T12:38:37.526+0000] {subprocess.py:93} INFO - [0m12:38:37  Installed from version 1.1.1
[2025-07-28T12:38:37.526+0000] {subprocess.py:93} INFO - [0m12:38:37  Updated version available: 1.3.0
[2025-07-28T12:38:37.527+0000] {subprocess.py:93} INFO - [0m12:38:37
[2025-07-28T12:38:37.527+0000] {subprocess.py:93} INFO - [0m12:38:37  Updates available for packages: ['dbt-labs/dbt_utils']
[2025-07-28T12:38:37.527+0000] {subprocess.py:93} INFO - Update your versions in packages.yml, then run dbt deps
[2025-07-28T12:38:38.154+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-28T12:38:38.168+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dbt_pipeline, task_id=dbt_deps, execution_date=20250727T000000, start_date=20250728T123835, end_date=20250728T123838
[2025-07-28T12:38:38.187+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-28T12:38:38.202+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
